// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5tDegR5ZzDIR3ThJqvJBc-T64BVIXqJ8',
    appId: '1:469397382564:web:8f3da3455bc80ab7c3cd31',
    messagingSenderId: '469397382564',
    projectId: 'controlemesada-fea29',
    authDomain: 'controlemesada-fea29.firebaseapp.com',
    storageBucket: 'controlemesada-fea29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiqmBoNX9FouupOtDHU9EyClnPoMbcpFc',
    appId: '1:469397382564:android:5926e183eaabe1f1c3cd31',
    messagingSenderId: '469397382564',
    projectId: 'controlemesada-fea29',
    storageBucket: 'controlemesada-fea29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcPiiRQ5cqmZAF0OUcsLszVwf0o9hQzqo',
    appId: '1:469397382564:ios:368c12f60b6c5cf6c3cd31',
    messagingSenderId: '469397382564',
    projectId: 'controlemesada-fea29',
    storageBucket: 'controlemesada-fea29.appspot.com',
    iosClientId: '469397382564-4o58ddg47djc888e6teqp40mod8u72o4.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcPiiRQ5cqmZAF0OUcsLszVwf0o9hQzqo',
    appId: '1:469397382564:ios:a3ff21cfdee88948c3cd31',
    messagingSenderId: '469397382564',
    projectId: 'controlemesada-fea29',
    storageBucket: 'controlemesada-fea29.appspot.com',
    iosClientId: '469397382564-nmvju8equl8nftvp7iam19pkdet921l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
